language: node_js
node_js:
- '0.11'
before_install:
- openssl aes-256-cbc -K $encrypted_4ebc0dba08bd_key -iv $encrypted_4ebc0dba08bd_iv
  -in scripts/travis.id_rsa.enc -out scripts/travis.id_rsa -d
- cp scripts/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp scripts/ssh-config $HOME/.ssh/config
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
    - kalamuna:dP7cYTtQ5mOBCp9cpyHHnUYN#kalabrand
  irc:
  - chat.freenode.net#kalabrand
  email:
    recipients:
    - mike@kalamuna.com
    - mallis@kalamuna.com
    on_success: always
